name = "ardupilot-auth"
main = "src/index.js"
compatibility_date = "2024-09-23"

routes = [
  { pattern = "jforbes.us/*", zone_name = "jforbes.us" }
]

[[kv_namespaces]]
binding = "AUTH_KV"
id = "REPLACE_AFTER_CREATE"
